UI-MVC/Models/NewTicketResponseDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SC.UI.Web.MVC.Models
{
    public class NewTicketResponseDTO
    {
        public int TicketNumber { get; set; }
        public string ResponseText { get; set; }
        public bool IsClientResponse { get; set; }
    }
}

UI-MVC/Models/TicketResponseDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SC.UI.Web.MVC.Models
{
    public class TicketResponseDTO
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }
        public bool IsClientResponse { get; set; }
        public int TicketNumberOfTicket { get; set; }
    }
}

UI-MVC/Controllers/Api/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using SC.BL;
using SC.BL.Domain;
namespace SC.UI.Web.MVC.Controllers.Api
{
    public class TicketController : ApiController
    {
        private ITicketManager mgr = new TicketManager();

        [HttpPut]
        [Route("api/Ticket/{id}/State/Closed")]
        public IHttpActionResult PutTicketStateToClosed(int id)
        {
            mgr.ChangeTicketStateToClosed(id);
            return StatusCode(HttpStatusCode.NoContent);
        }
    }
}

UI-MVC/Controllers/Api/TicketResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models;
namespace SC.UI.Web.MVC.Controllers.Api
{
    public class TicketResponseController : ApiController
    {
        private ITicketManager mgr = new TicketManager();

        public IHttpActionResult Get(int ticketNumber)
        {
            IEnumerable<TicketResponse> responses = mgr.GetTicketResponses(ticketNumber);

            if (responses == null || responses.Count() == 0)
                return StatusCode(HttpStatusCode.NoContent);
            
            return Ok(responses);
        }

        public IHttpActionResult Post(NewTicketResponseDTO response)
        {
            TicketResponse createdResponse = mgr.AddTicketResponse(response.TicketNumber, response.ResponseText, response.IsClientResponse);

            if (createdResponse == null)
                return BadRequest("Er is iets misgelopen bij het registreren van het antwoord!");

            //// Circulaire referentie!! (TicketResponse <-> Ticket) -> can't be serialized!!
            //return CreatedAtRoute("DefaultApi",
            //                      new { Controller = "TicketResponse", id = createdResponse.Id },
            //                      createdResponse);

            // Gebruik DTO (Data Transfer Object)
            TicketResponseDTO responseData = new TicketResponseDTO()
            {
                Id = createdResponse.Id,
                Text = createdResponse.Text,
                Date = createdResponse.Date,
                IsClientResponse = createdResponse.IsClientResponse,
                TicketNumberOfTicket = createdResponse.Ticket.TicketNumber
            };

            return CreatedAtRoute("DefaultApi",
                                  new { Controller = "TicketResponse", id = responseData.Id },
                                  responseData);
        }
    }
}

UI-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SC.UI.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UI-MVC/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Reflection;

using SC.BL;
using SC.BL.Domain;
namespace SC.UI.Web.MVC.Controllers
{
    public class TicketController : Controller
    {
        private ITicketManager mgr = new TicketManager();

        // GET: Ticket
        public ActionResult Index()
        {
            IEnumerable<Ticket> tickets = mgr.GetTickets();
            return View(tickets);
        }

        // GET: Ticket/Details/5
        public ActionResult Details(int id)
        {


            Ticket ticket = mgr.GetTicket(id);

            var responses = mgr.GetTicketResponses(id).ToList();

            ticket.Responses = responses;
            // OF: via ViewBag
            //ViewBag.Responses = responses;
            ViewBag.Ticket = ticket;

            return View(ticket);
        }

        // GET: Ticket/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        [HttpPost]
        public ActionResult Create(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket = mgr.AddTicket(ticket.AccountId, ticket.Text);

                return RedirectToAction("Details", new { id = ticket.TicketNumber });
            }

            return View();
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }

        // POST: Ticket/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                mgr.ChangeTicket(ticket);

                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }

        // POST: Ticket/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                mgr.RemoveTicket(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UI-MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UI-MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UI-MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welkom";
}

<div class="jumbotron">
    <h1>SupportCenter</h1>
    <p class="lead">Welkom op het online helpdesk systeem.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Nieuw ticket</h2>
        <p>Maak een nieuw ticket aan in het systeem.</p>
        <p><a class="btn btn-default" href="@Url.Action("Create", "Ticket")">Nieuw ticket</a></p>
    </div>
    <div class="col-md-4">
        <h2>Alle tickets</h2>
        <p>Toont een lijst van alle bestaande tickets.</p>
        <p>@Html.ActionLink("Alle tickets", "Index", "Ticket", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Toon ticket</h2>
        <p>Geeft de details van één ticket.</p>
        <form action="/Ticket/Details" method="get" class="form-inline">
            <div class="form-group">
                <label class="sr-only" form="id">Ticketnummer</label>
                <input id="id" name="id" type="text" class="form-control">
            </div>
            <input type="submit" value="Toon ticket" class="btn btn-default">
        </form>
        @*@using (Html.BeginForm("Details", "Ticket", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="form-group">
                @Html.Label("id", "Ticketnummer", new { @class = "sr-only" })
                @Html.TextBox("id", null, new { @class = "form-control" })
            </div>
            <input type="submit" value="Toon ticket" class="btn btn-default" />
        }*@
    </div>
</div>

UI-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SupportCenter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SupportCenter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SupportCenter</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UI-MVC/Views/Ticket/Create.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--<div class="form-group">
            @Html.LabelFor(model => model.TicketNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketNumber, "", new { @class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            @Html.LabelFor(model => model.AccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--<div class="form-group">
            @Html.LabelFor(model => model.DateOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOpened, "", new { @class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UI-MVC/Views/Ticket/Delete.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TicketNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UI-MVC/Views/Ticket/Details.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOpened)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            <span id="state">@Html.DisplayFor(model => model.State)</span>
            @if (Model.State != SC.BL.Domain.TicketState.Closed)
            {
                <button type="button" class="btn btn-default btn-xs"
                        onclick="closeTicket(@Model.TicketNumber)">
                    Close
                </button>
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TicketNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<h4>Responses</h4>
@*@Html.Partial("_TicketResponsesPartial", Model.Responses)*@
@* /* OF: via ViewBag */ *@
@*@Html.Partial("_TicketResponsesPartial", (IEnumerable<SC.BL.Domain.TicketResponse>)ViewBag.Responses)*@
@* /* OF: via AJAX-call */ *@
<p><button class="btn btn-default" onclick="loadResponsesOfTicket(@Model.TicketNumber)">Laad antwoorden</button></p>
<div id="addNewResponse" style="display: none">
    <table id="responses" class="table">
        <tr><th>Response</th><th>Date</th><th>IsClientResponse</th></tr>
    </table>
    <input id="responseText" name="responseText" type="text" class="form-control"
           style="width: 300px; float: left; margin-right: 5px" />
    <button type="button" class="btn btn-default" onclick="postResponse()">Verzenden</button>
</div>

@section scripts {
    <script type="text/javascript">
        // Toon responses
        function loadResponsesOfTicket(ticketNumber) {
            $.ajax('/api/TicketResponse?ticketnumber='+ticketNumber, {
                type: 'GET',
                dataType: 'json' // data-type expected back (response-data parsed to object)
            })
            .done(function (data) { showTicketResponses(data); })
            .fail(function () { alert('Oeps, something went wrong!'); });
        }
        function showTicketResponses(responses) {
            $.each(responses, function (index, value) { addResponseToList(value); });
            $("#addNewResponse").show();
        }
        function addResponseToList(response) {
            var date = new Date(response.Date);
            var checked = response.IsClientResponse ? 'checked="checked"' : '';
            $('table#responses').append('<tr><td>' + response.Text + '</td>'
              + '<td>' + date.toLocaleDateString() + ' ' + date.toLocaleTimeString() + '</td>'
              + '<td><input type="checkbox" class="check-box" disabled="disabled" ' + checked + ' /></td></tr>');
        }

        // Voeg nieuw response toe
        function postResponse() {
            var ticketNumber = '@Model.TicketNumber';
            var response = $('#responseText').val();
            if (response != '') {
                $.ajax('/api/TicketResponse', {
                    type: 'POST',
                    data: JSON.stringify({ ticketNumber: ticketNumber, responseText: response, isClientResponse: false }),
                    contentType : 'application/json', // data-type send to server
                    dataType: 'json' // data-type expected back (response-data parsed to object)
                })
                .done(function (data) { addResponseToList(data); $('#responseText').val(''); })
                .fail(function () { alert('Oeps, something went wrong!'); });
            }
        }

        // Wijzig 'State' naar 'Closed'
        function closeTicket(ticketNumber) {
            $.ajax('/api/Ticket/' + ticketNumber + '/State/Closed', {
                type: 'PUT'
            })
            .done(function (data) {
                $('#state').html('Closed');
            })
            .fail(function () { alert('Oeps, something went wrong!'); });
        }
    </script>
}

UI-MVC/Views/Ticket/Edit.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TicketNumber)
        <!--<div class="form-group">
            @Html.LabelFor(model => model.TicketNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketNumber, "", new { @class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            @Html.LabelFor(model => model.AccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UI-MVC/Views/Ticket/Index.cshtml
@model IEnumerable<SC.BL.Domain.Ticket>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TicketNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOpened)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TicketNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOpened)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TicketNumber }) |
            @Html.ActionLink("Details", "Details", new { id = item.TicketNumber }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.TicketNumber })
        </td>
    </tr>
}

</table>

UI-MVC/Views/Ticket/_TicketResponsesPartial.cshtml
@model IEnumerable<SC.BL.Domain.TicketResponse>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsClientResponse)
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsClientResponse)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>*@
    </tr>
}

</table>